# Generated by Django 5.0.4 on 2024-04-06 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FichaMedica',
            fields=[
                ('rut', models.CharField(max_length=10, primary_key=True, serialize=False, verbose_name='Rut')),
                ('nombres', models.CharField(max_length=64, verbose_name='Nombres')),
                ('apellidos', models.CharField(max_length=64, verbose_name='Apellidos')),
                ('direccion', models.CharField(max_length=128, verbose_name='Dirección')),
                ('ciudad', models.CharField(max_length=32, verbose_name='Ciudad')),
                ('telefono', models.CharField(max_length=12, verbose_name='Teléfono')),
                ('email', models.CharField(max_length=64, verbose_name='Email')),
                ('fechaNac', models.DateField(verbose_name='Fecha de Nacimiento')),
                ('estadoCivil', models.CharField(max_length=32, verbose_name='Estado Civil')),
                ('comentarios', models.CharField(max_length=256, verbose_name='Comentarios')),
            ],
            options={
                'verbose_name': 'Ficha Médica',
                'verbose_name_plural': 'Fichas Médicas',
                'db_table': 'FichaMedica',
                'ordering': ['nombres'],
            },
        ),
    ]
